"""Ephemeral poll token primitives.

Poll tokens are short-lived read-only credentials for monitor processes. They
are deliberately separate from agent API keys:

* raw format is ``nxsept_`` + 64 lowercase hex chars (256 bits);
* only the SHA-256 hash may be persisted;
* a cheap shape check lets HTTP auth route them away from the permanent-key
  path without treating shape as authentication.
"""

from __future__ import annotations

import hashlib
import secrets

POLL_TOKEN_PREFIX = "nxsept_"
_TOKEN_BYTES = 32
_TOKEN_HEX_LEN = _TOKEN_BYTES * 2
_HEX_DIGITS = frozenset("0123456789abcdef")


def generate_poll_token() -> str:
    """Return a fresh ephemeral poll token."""
    return POLL_TOKEN_PREFIX + secrets.token_hex(_TOKEN_BYTES)


def hash_poll_token(token: str) -> str:
    """Return the lowercase SHA-256 hex digest for ``token``."""
    return hashlib.sha256(token.encode("utf-8")).hexdigest().lower()


def is_well_formed_poll_token(value: str) -> bool:
    """Whether ``value`` has the shape generated by this module."""
    if not isinstance(value, str) or not value.startswith(POLL_TOKEN_PREFIX):
        return False
    token = value[len(POLL_TOKEN_PREFIX) :]
    if len(token) != _TOKEN_HEX_LEN:
        return False
    return all(ch in _HEX_DIGITS for ch in token)
