"""Atomic pool/queue ports, suitable for local or distributed adapters.

All methods participate in ONE serializable transaction supplied by the caller.
Admission, dequeue, capacity claim and durable outcome must commit together.
An adapter must not acknowledge a dequeue independently of its reservation.
Network/process effects belong outside that transaction, via the execution
outbox. Resource release requires a correlated, fenced disposal proof supplied
by the execution adapter; neither timeout nor a lost worker proves disposal.
"""
from typing import Protocol

from ..domain.resource_pool import PoolInstance, PoolPolicy, PoolRequest


class RequestQueue(Protocol):
    def get(self, request_id: str) -> PoolRequest | None: ...
    def add(self, request: PoolRequest) -> None: ...
    def save(self, request: PoolRequest) -> None: ...
    def waiting(self, *, host_id: str, limit: int) -> list[PoolRequest]: ...
    def waiting_count(self, *, pool_id: str | None = None, host_id: str | None = None) -> int: ...
    def preparing_count(self, *, pool_id: str, host_id: str | None = None,
                        configuration: str | None = None) -> int: ...
    def expired(self, *, host_id: str, now: float, limit: int) -> list[PoolRequest]: ...
    def timed_out(self, *, host_id: str, now: float, limit: int) -> list[PoolRequest]: ...
    def outcomes(self, *, caller_id: str, limit: int) -> list[dict]: ...
    def acknowledge(self, *, caller_id: str, request_id: str, now: float) -> bool: ...


class InstancePool(Protocol):
    def get(self, instance_id: str) -> PoolInstance | None: ...
    def for_request(self, request_id: str) -> PoolInstance | None: ...
    def add(self, instance: PoolInstance) -> None: ...
    def save(self, instance: PoolInstance) -> None: ...
    def remove(self, instance_id: str) -> None: ...
    def count(self, *, pool_id: str | None = None, host_id: str | None = None) -> int: ...
    def warm(self, *, pool_id: str, host_id: str, configuration: str) -> PoolInstance | None: ...
    def idle(self, *, pool_id: str) -> list[PoolInstance]: ...
    def incompatible(self, *, pool_id: str, host_id: str, configuration: str,
                     binding_id: str | None) -> list[PoolInstance]: ...
    def states(self, *, pool_id: str, host_id: str) -> dict[str, int]: ...
    def closing_count(self, *, pool_id: str) -> int: ...


class PoolTransaction(Protocol):
    requests: RequestQueue
    instances: InstancePool

    def require_write(self) -> None: ...
    def policy(self, pool_id: str) -> PoolPolicy: ...
    def backoff(self, *, pool_id: str, host_id: str) -> tuple[int, float]: ...
    def save_backoff(self, *, pool_id: str, host_id: str, failures: int, until: float) -> None: ...
    def clear_backoff(self, *, pool_id: str, host_id: str) -> None: ...
